dataset: cais/hle

provider: vllm # [vllm]

base_url: http://localhost:8000/v1

# model: Qwen/Qwen3-32B
model: /home/Competition2025/P12/P12U007/model/Qwen3-32B-SFT-GRPO
# model: Qwen/QwQ-32B
# model: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
# model: Qwen/Qwen3-32B
max_completion_tokens: 100000
reasoning: true

# sample with multimodal is 2500, so text-only sample is about 2400
num_workers: 200
max_samples: 2500

judge: o3-mini-2025-01-31

# 記載されたカテゴリのみ評価
# 一例
# category_filter:
#     - "Math"
#     - "Physics"
#     - "Humanities/Social Science"
#     - "Engineering"
#     - "Chemistry"
#     - "Biology/Medicine"
#     - "Computer Science/AI"
#     - "Other"

# category_filter:
#    - "Math"

# 前解き終わらなかった回答を解かせたいときに使う
duplicate_filter: True

# 回答のidを見ることでどの問題が解き終わらなかったのかを見る
# 前解き終わらなかった回答を解かせたいときに使う
duplicate_file: /home/Competition2025/P12/P12U007/eval_hle/eval_hle/predictions/hle_Qwen3-32B-SFT-GRPO_20250810_054303.json
category_filter: null

# category_filter:
#     - "Physics"
#     - "Humanities/Social Science"
#     - "Engineering"
#     - "Chemistry"
#     - "Biology/Medicine"
#     - "Computer Science/AI"
#     - "Other"

